#!/usr/bin/python3
# -*- coding: utf-8 -*-
import requests
import json
import pymysql

# 连接数据库
connection = pymysql.connect(host='localhost',
                             port=3306,
                             user='root',
                             passwd='root',
                             db='python',
                             charset='utf8')

cursor = connection.cursor()
sql = "USE python;"
cursor.execute(sql)
connection.commit()
#创建表

try:
    movies = '''
        CREATE TABLE douban(
            ID  VARCHAR (255) NOT NULL PRIMARY KEY,
            text VARCHAR (255),
            rate VARCHAR (255) 
        )
    '''
    # 序号 INT  NOT NULL PRIMARY KEY AUTO_INCREMENT,
    cursor.execute(movies)
    connection.commit()
except Exception as e:
    print(e)
    pass

# 定义请求url
url = "https://movie.douban.com/j/search_subjects"
# 定义请求头
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"
}
# 循环构建请求参数并且发送请求
num=0
for page_start in range(0, 100, 20):
    params = {
        "type": "movie",
        "tag": "热门",
        "sort": "recommend",
        "page_limit": "20",
        "page_start": page_start
    }
    response = requests.get(
        url=url,
        headers=headers,
        params=params
    )
    # 方式一:直接转换json方法
    # results = response.json()
    # 方式二: 手动转换
    # 获取字节串
    content = response.content
    # 转换成字符串
    string = content.decode('utf-8')
    # 把字符串转成python数据类型
    results = json.loads(string)
    # 解析结果
    for movie in results["subjects"]:
        num+=1
        print(num,movie["title"], movie["rate"])
        movies=(num,movie["title"],movie["rate"])
        try:
            sql = '''INSERT INTO douban (ID,text,rate)
                  VALUES (%s,%s,%s) '''
            cursor.execute(sql,movies)
            connection.commit()
        except Exception as e:
            print(e)
            pass

sql = '''SELECT * from  douban order by rate desc'''
count=cursor.execute(sql)
for i in range(count):
    print(i,cursor.fetchone())
